name: smartexpense
description: "Smart Expense Tracker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  http: ^1.2.1                    # Add this
  shared_preferences: ^2.2.3      # Add this           # Add this

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true