name: smartexpense
description: "SmartExpense - Personal Finance Tracker with OCR"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  http: ^1.2.1                    
  shared_preferences: ^2.2.3
  pdf: ^3.10.8                    
  printing: ^5.12.0               
  path_provider: ^2.1.2           
  share_plus: ^7.2.2              
  open_file: ^3.3.2       

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

  # App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#00C853"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  min_sdk_android: 21

# Splash Screen Configuration  
flutter_native_splash:
  color: "#00C853"
  image: "assets/icon/splash_logo.png"
  android_12:
    color: "#00C853"
    image: "assets/icon/splash_logo.png"